[pytest]
addopts = -vs --html=./report/login_report.html --self-contained-html
          ; --clean-alluredir --alluredir=report/allure-results
          ; --alluredir report -p no:warnings
testpaths = ./script
python_files = test_kd_login.py
python_classes = Test* test*
python_functions = test* test_*