[pytest]
addopts = -vs --html=./report/login_report.html --self-contained-html
          --clean-alluredir --alluredir=report
testpaths = ./script
python_files = test_*
python_classes = Test* test*
python_functions = test* test_*